### ISSUE TITLE
Provide easy plot methods for all result types

### ISSUE THREAD

**Issue by Ozaq** [PedestrianDynamics/PedPy#210]
We are missing the following easy plot methods:

* `plot_nt`
* `plot_density`
* `plot_speed`
* `plot_passing_density`
* `plot_flow`
* `plot_neighborhood`
* `plot_distance_to`
* `plot_profiles`

**Comment by schroedtert** [comment]
Closed with 67a0bc16e15ff6212cf0b01476eb7216242a03fe
