### ISSUE TITLE
plot_voronoi_cell: missing argument

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/PedPy#224]
According to the latest API documentation:
https://pedpy.readthedocs.io/en/latest/api/plotting.html#plotting.plot_voronoi_cells

the function `plot_voronoi_cells` has no option `show_ped_positions`.
However, [Gettstarted](https://pedpy.readthedocs.io/en/stable/getting_started.html) uses this option:

<img width="424" alt="Screenshot 2023-09-26 at 05 49 08" src="https://github.com/PedestrianDynamics/PedPy/assets/5772973/833f550a-61f2-4e69-a84e-30094a86cd41">

Probably the Getting_started should be updated.

**Comment by Ozaq** [comment]
Good catch, show_ped_positions is not part of the API any longer and should be removed from the guide. If you do not want to plot agent positions you need to omit `traj_data`, i.e. if no agent positions are provided none are plotted.
