### ISSUE TITLE
Enhance plots for Distance/Time  to entrance with colors

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/PedPy#309]
I suggest adding colors w.r.t to speed in the plots of the [time/distance to entrance](https://pedpy.readthedocs.io/en/stable/user_guide.html#distance-to-entrance-time-to-entrance)

The result may look like this 
<img width="511" alt="Screenshot 2024-03-20 at 13 01 54" src="https://github.com/PedestrianDynamics/PedPy/assets/5772973/c0ab91a6-49e6-4797-b743-e9d4ce7c1452">

What do you think?
@JuleAdrian, @schroedtert

**Comment by JuleAdrian** [comment]
Yes, I like it and I think both color options should be available.
