### ISSUE TITLE
Revisit calculate_data_frame_pair_dist

### ISSUE THREAD

**Issue by schroedtert** [PedestrianDynamics/PedPy#345]
After a short glance at the new feature, I saw the function `calculate_data_frame_pair_dist`. I have some questions remarks, we should address before the 1.2.0 release. As after the release we are stuck with the name and parameter of the function.

- Is it intended that the function has public visibility? 
  - no: make it private by adding a `_` before the function name (easiest way)

If yes some more things need a refactoring:
- Naming pattern of the function:
  -  It should start with `compute` as all (hopefully) other compute functions
  - No need to add the data frame in the name
  - no abbreviations in the name, this might lead to confusion!
  - suggestion: `compute_pair_wise_distances`
- the interface should use `TrajectoryData` instead of `DataFrame`. The function is using the same columns anyway.
- the return value should be a `DataFrame`, suggested columns (`frame`, `id`, `other_id` or `neighbor_id`, `distance`) 
- then resolving this would also close #246 

Sorry that I only saw it after the PR was merged, my bad.

**Comment by schroedtert** [comment]
In Python only functions with a leading `_` are private. So renaming will resolve this issue from my side

**Comment by chraibi** [comment]
closed by #350
