### ISSUE TITLE
Use time as parameter velocity API instead of frame

### ISSUE THREAD

**Issue by schroedtert** [PedestrianDynamics/pedpy#61]
As the frame rate may change in different trajectory files it may be easier to directly use the time frame as parameter instead of the frame step in the velocity computation API.

**Comment by schroedtert** [comment]
**Need to be discussed:**

What happens when the time step can not be divided by the frame rate? 

**Example:**
frame rate: 10 fps
time step: 0.25s

frame range: 2 (0.2s) or 3 (0.3s)

**Comment by chraibi** [comment]
The result of the discussion was that we will stick with frames instead.
