### ISSUE TITLE
Enforce type hints in functions

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/PedPy#97]
In the notebook: Usage 

```
traj = parse_trajectory(trajectory_file="demos/uni-directional/traj_UNI_CORR_500_01.txt")
```

trajectory_file is Str but 
```
def parse_trajectory(
    *, trajectory_file: pathlib.Path, frame_rate: float = None, default_unit: TrajectoryUnit = None
) 
```
Expects a Path. 

How to enforce a proper use of this function?

**Comment by chraibi** [comment]
Suggestion using [typen](https://pypi.org/project/typen/)

```
from typen import strict_type_hints
from typen.exceptions import ParameterTypeError


@strict_type_hints
def add(a: int, b: int) -> int:
    return a+b


print(f"OK {add(1, 1)}")
try:
    print(f"NOT OK {add(1, 1.2)}")
except ParameterTypeError as err:
    print(err)
```

**Comment by schroedtert** [comment]
This is an issue, we will always have with Python. Currently we enforce, the type hints in the function definition with MyPy. `typen` looks good, but doesn't seem to be under active development (last commit Jan 2020).
